- name: Deploy ACR for AIHACK
  hosts: localhost
  connection: local

  tasks:

  - name: Make sure Deep Learning VM Resource Group Exists
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Create an Azure Container Registry
    azure_rm_containerregistry:
      name: "{{ vm_name }}acr{{ lookup('env', 'USER') }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      state: present
      admin_user_enabled: true
      sku: Basic
    register: output

  - debug:
      msg: "YOUR ACR USERNAME IS: {{ output['name'] }}"

  - debug:
      msg: "YOUR ACR PASSWORD IS: {{ output['credentials']['password'] }}"
