- name: Deploy AKS for AIHACK
  hosts: localhost
  connection: local

  tasks:

  - name: Make sure Deep Learning VM Resource Group Exists
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Create a managed Azure Container Services (AKS) instance
    azure_rm_aks:
      name: "{{ vm_name }}-k8s"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ vm_name }}-k8s-{{ lookup('env', 'USER') }}"
      linux_profile:
        admin_username:  "{{ admin_username }}"
        ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      service_principal:
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      agent_pool_profiles:
        - name: default
          count: "{{ k8s_vm_count }}"
          vm_size: "{{ k8s_vm_size }}"
