- name: Determine IP address of provisioned DLVM
  hosts: localhost
  connection: local
  tasks:

    - name: Getting Public IP address of Deep Learning VM
      azure_rm_publicipaddress_facts:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-pip"
      register: output

    - name: Adding Public IP to Ansible host group
      add_host:
        hostname: "{{ output.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
        groups: ado-dlvm

    - name: Setting Public IP variable
      set_fact:
        dlvm_ip: "{{ output.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"  

- name: Run train.py and create PKL file using provisioned DLVM 
  hosts: ado-dlvm
  remote_user: "{{ admin_username }}"
  become: yes  
  tasks:

    - name: Create git clone directory
      file:
        path: "/home/{{ admin_username }}/repo"
        state: directory

    - name: Clone git repository
      git:
        repo: "{{ git_repo }}"
        dest: "/home/{{ admin_username }}/repo"
        clone: yes
        force: yes

    - name: Run train.py script to generate PKL file
      command: "/data/anaconda/envs/py35/bin/python ds_artifacts/train.py" 
      args:
        chdir: "/home/{{ admin_username }}/repo"

- name: Copy generated PKL files from DLVM to local directory in ADO and push to GitHub
  hosts: localhost
  connection: local
  tasks:

    - name: Determine Date/Time stamp
      command: "date +%Y%m%d%H%M%S"
      register: dateoutput

    - name: Setting Date/Time stamp to a variable
      set_fact:
        datestamp: "{{ dateoutput.stdout }}"

    - name: "Copying all PKL files generated on DLVM to the output directory 'pkl-output'"
      command: "scp -v {{ admin_username }}@{{ dlvm_ip }}:/home/{{ admin_username }}/repo/ds_artifacts/*.pkl {{ lookup('env', 'WORKING_DIR') }}/ds_artifacts"

    - name: "Adding all PKL files to GitHub payload"
      command: "git add *.pkl"
      args:
        chdir: "{{ lookup('env', 'WORKING_DIR') }}/ds_artifacts"

    - name: "Committing all PKL files to GitHub repository"
      command: "git commit -m 'PKL files generated {{ datestamp }}'"
      args:
        chdir: "{{ lookup('env', 'WORKING_DIR') }}"

    - name: "Setting GitHub credentials"
      command: "git remote set-url origin https://{{ git_user }}:{{ git_token }}@github.com/{{ git_user }}/aidevopshack"
      args:
        chdir: "{{ lookup('env', 'WORKING_DIR') }}"

    - name: "Pushing PKL files to GitHub repository"
      command: "git push origin master"
      args:
        chdir: "{{ lookup('env', 'WORKING_DIR') }}"

